<a href="https://colab.research.google.com/github/amarshivangol/Complete-Python-3-Bootcamp/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install pandas


In [2]:
pip install numpy

In [0]:
import numpy as np

In [0]:
A=np.zeros(10)
A[3]=2

In [16]:
type(A)

builtin_function_or_method

In [18]:
A

<function numpy.arange>

In [0]:
A=np.arange(10,50)

In [32]:
A

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [0]:
A=A[::-1]

In [34]:
A

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [0]:
A=np.arange(8).reshape(4,2)

In [37]:
A

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [0]:
A=np.arange(9).reshape(3,3)

In [39]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [0]:
A=np.arange(8).reshape(2,4)

In [41]:
A

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [0]:
A=np.arange(8).reshape(2,2,2)

In [48]:
A

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [0]:
A=np.nonzero([1,2,0,0,4,0])

In [50]:
A # non-zero indexes are found.

(array([0, 1, 4]),)

In [0]:
A=np.eye(2)# identity matrix(principal diagonal are ones and all other elements are zeros.)

In [52]:
A

array([[1., 0.],
       [0., 1.]])

In [0]:
A=np.eye(3)

In [54]:
A

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [0]:
A=np.random.random((3,3,3,))

In [57]:
A

array([[[0.02563074, 0.54812189, 0.64206826],
        [0.67417129, 0.64816526, 0.99344292],
        [0.59380803, 0.5836024 , 0.8788    ]],

       [[0.91643661, 0.7669077 , 0.42277974],
        [0.57194503, 0.77875471, 0.91074377],
        [0.14797267, 0.58920013, 0.8806015 ]],

       [[0.83889248, 0.77102233, 0.9628203 ],
        [0.66208621, 0.86966338, 0.117129  ],
        [0.68094866, 0.0661088 , 0.00360808]]])

In [0]:
A=np.random.random((3,3,3,))

In [61]:
A

array([[[0.81703231, 0.88154491, 0.80796565],
        [0.33677658, 0.18174711, 0.61917551],
        [0.47696038, 0.81771049, 0.4504171 ]],

       [[0.77123428, 0.9227855 , 0.21166096],
        [0.72711099, 0.31136875, 0.04331947],
        [0.17071491, 0.42992245, 0.4145173 ]],

       [[0.25789994, 0.77677746, 0.82051419],
        [0.75513804, 0.38820319, 0.11620407],
        [0.94191185, 0.21484842, 0.42758301]]])

In [63]:
A.min()

0.04331947061828456

In [64]:
A.max()

0.9419118467006083

In [66]:
A.mean()

0.521890547882188

In [0]:
A=np.ones((5,5))

In [68]:
A

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [0]:
A[1:-1,1:-1]=0

In [70]:
A

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [71]:
list1=[2,3,4,5,6]
list1[2:4]

[4, 5]

In [0]:
A[2:3,1:-1]=0

In [73]:
A

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [0]:
A[2:3]=0

In [75]:
A

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [76]:
list1=[2,3,4,5,6]
list1[2:4]

[4, 5]

In [0]:
A[2:]=0

In [0]:
A[:,2:]=0

In [79]:
A

array([[1., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [81]:
list1=[2,3,4,5,6,7,8,9,10,11,12,13]
list1[2:7:2]

[4, 6, 8]

In [0]:
A=A[::-1]

In [84]:
A

array([[1., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [86]:
A=[(1,2,3),(4,5)]
type(A)

list

In [92]:
X=np.asarray(A)
type(X)

numpy.ndarray

In [93]:
numpy.ndarray

NameError: ignored

In [0]:
S='Hello world'.split()

In [100]:
S

['Hello', 'world']

In [99]:
A=np.frombuffer(S,dtype='S1')

TypeError: ignored

In [0]:
X=[np.nan,1,2,np.nan,3,4,5]

In [102]:
X

[nan, 1, 2, nan, 3, 4, 5]

In [0]:
list1=[]

In [109]:
X[~np.isnan(X)]

TypeError: ignored

In [0]:
import pandas as pd

In [0]:
Dataframe=pd.DataFrame()

In [112]:
list1

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

In [0]:
Daatframe['list1']

In [0]:
house=pd.read_json('/content/sample_data/anscombe.json')

In [123]:
house.describe()

X          Y
count  44.000000  44.000000
mean    9.000000   7.500455
std     3.198837   1.959244
min     4.000000   3.100000
25%     7.000000   6.117500
50%     8.000000   7.520000
75%    11.000000   8.747500
max    19.000000  12.740000

In [124]:
house.head()

Series   X     Y
0      I  10  8.04
1      I   8  6.95
2      I  13  7.58
3      I   9  8.81
4      I  11  8.33

In [125]:
house.shape

(44, 3)

In [126]:
%time 2**3

CPU times: user 4 µs, sys: 0 ns, total: 4 µs
Wall time: 6.44 µs


8

In [127]:
%time np.power(2,3)

CPU times: user 36 µs, sys: 3 µs, total: 39 µs
Wall time: 40.8 µs


8